export type Planet = "Sun" | "Moon" | "Mars" | "Mercury" | "Jupiter" | "Venus" | "Saturn" | "Rahu" | "Ketu"
export type House = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12

const base: Record<Planet, Record<House, string>> = {
  Sun: {
    1: "Confident, authoritative.",
    2: "Wealth gain, possible disputes.",
    3: "Courageous communication.",
    4: "Strong will at home.",
    5: "Creative leadership.",
    6: "Victory over obstacles.",
    7: "Dominant in partnerships.",
    8: "Transformative ego lessons.",
    9: "Righteous leadership.",
    10: "Career authority.",
    11: "Influential networks.",
    12: "Spiritual illumination.",
  },
  Moon: {
    1: "Emotional, nurturing presence.",
    2: "Fluctuating wealth, soft speech.",
    3: "Empathetic communication.",
    4: "Strong attachment to home.",
    5: "Creative imagination.",
    6: "Service with empathy.",
    7: "Sensitive partnerships.",
    8: "Deep emotional tides.",
    9: "Faith through intuition.",
    10: "Public mood influence.",
    11: "Supportive friends.",
    12: "Dreamy, reflective.",
  },
  Mars: {
    1: "Energetic, assertive.",
    2: "Bold with resources.",
    3: "Dynamic communication.",
    4: "Protective at home.",
    5: "Passionate creativity.",
    6: "Competent in conflicts.",
    7: "Fiery relationships.",
    8: "Intense transformation.",
    9: "Driven beliefs.",
    10: "Ambitious career.",
    11: "Bold alliances.",
    12: "Hidden drive.",
  },
  Mercury: {
    1: "Quick intellect.",
    2: "Skilled with finances.",
    3: "Eloquent and witty.",
    4: "Analytical at home.",
    5: "Intelligent creativity.",
    6: "Sharp problem solving.",
    7: "Negotiation talent.",
    8: "Research-focused.",
    9: "Teaching and learning.",
    10: "Smart reputation.",
    11: "Networked thinker.",
    12: "Subconscious analysis.",
  },
  Jupiter: {
    1: "Wise and generous.",
    2: "Wealth expansion.",
    3: "Ethical communication.",
    4: "Nourishing wisdom at home.",
    5: "Abundant creativity.",
    6: "Service with integrity.",
    7: "Blessed partnerships.",
    8: "Spiritual rebirth.",
    9: "Philosophical dharma.",
    10: "Respected mentor.",
    11: "Benefic circles.",
    12: "Moksha inclination.",
  },
  Venus: {
    1: "Attractive charm.",
    2: "Luxurious tastes.",
    3: "Artful speech.",
    4: "Aesthetic home.",
    5: "Romantic creativity.",
    6: "Harmonious service.",
    7: "Pleasure in union.",
    8: "Sensual mystique.",
    9: "Beauty in faith.",
    10: "Elegant career.",
    11: "Pleasant friendships.",
    12: "Hidden pleasures.",
  },
  Saturn: {
    1: "Disciplined persona.",
    2: "Careful with wealth.",
    3: "Measured communication.",
    4: "Structured home life.",
    5: "Serious creativity.",
    6: "Dutiful service.",
    7: "Karmic partnerships.",
    8: "Profound endurance.",
    9: "Lawful conviction.",
    10: "Slow steady career.",
    11: "Mature networks.",
    12: "Detached introspection.",
  },
  Rahu: {
    1: "Innovative persona.",
    2: "Unconventional wealth.",
    3: "Edgy communication.",
    4: "Unusual home patterns.",
    5: "Experimental creation.",
    6: "Nonlinear service path.",
    7: "Unorthodox relations.",
    8: "Sudden changes.",
    9: "Rebel philosophies.",
    10: "Outlier status.",
    11: "Avant-garde circles.",
    12: "Foreign fascinations.",
  },
  Ketu: {
    1: "Detached individuality.",
    2: "Non-attachment to wealth.",
    3: "Mystic speech.",
    4: "Otherworldly home.",
    5: "Spiritual creativity.",
    6: "Karmic service.",
    7: "Detached unions.",
    8: "Occult insight.",
    9: "Ascetic tendencies.",
    10: "Silent mastery.",
    11: "Subtle networks.",
    12: "Liberation focus.",
  },
}

export default base
